version: "3.7"

services:
  mysql:
    image: "mysql:5.6"
    container_name: "local-mysql"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - "mysql_data_vol:/var/lib/mysql"
      - "./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro"
    restart: unless-stopped
    networks:
      - mysql_net
networks:
  mysql_net:
    external:
      name: mysql_net

volumes:
  mysql_data_vol: