version: '3.7'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: always
    volumes:
      - data:/app/data/
      - ./config.toml:/app/config.toml
volumes:
  data:      