version: "3.8"

services:
  mysql:
    image: "mysql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - "mysql_data_vol:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - mysql_net
networks:
  mysql_net:

volumes:
  mysql_data_vol: