version: "3.8"

services:
  mysql:
    image: "mysql"
    container_name: "local-mysql"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - "mysql_data_vol:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - mysql_net
networks:
  mysql_net:
    external:
      name: mysql_net

volumes:
  mysql_data_vol: