version: "3.7"

serivces:
  web_server:
    image: "ngnix"
    ports:
      - "80:80"
    volumes:
      - "./conf/conf.d:/etc/nginx/conf.d"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/enable-php.conf:/etc/nginx/enable-php.conf"
      - "./conf/fastcgi.conf:/etc/nginx/fastcgi.conf"
      - "/etc/letsencrypt/live:/etc/letsencrypt/live"
      - "./wwwroot:/home/wwwroot"
    restart: unless-stopped
    networks:
      - ngnix_with_php_net
  php_driver:
    image: "php:5.6-fpm"
    restart: unless-stopped
    networks:
      - ngnix_with_php_net
networks:
    ngnix_with_php_net:
    